# Predict Titanic Survival
The RMS Titanic set sail on its maiden voyage in 1912, crossing the Atlantic from Southampton, England to New York City. The ship never completed the voyage, sinking to the bottom of the Atlantic Ocean after hitting an iceberg, bringing down 1,502 of 2,224 passengers onboard.

In this project you will create a Logistic Regression model that predicts which passengers survived the sinking of the Titanic, based on features like age and class.

The data we will be using for training our model is provided by Kaggle. Feel free to make the model better on your own and submit it to the Kaggle Titanic competition!

In [1]:
# Load the modules
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

## 1 
The file passengers.csv contains the data of 892 passengers onboard the Titanic when it sank that fateful day. Let’s begin by loading the data into a pandas DataFrame named passengers. Print passengers and inspect the columns. What features could we use to predict survival?

In [2]:
# importing the data
df = pd.read_csv('passengers.csv')
df.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

**Mike:** The columns to use are the numeric columns and any that can be converted to categorical variables (PassengersId. Survived, Pclass, Sex, Age, SinSp, Parch, Fare, Embarked), where the target is Survived.

## 2
Given the saying, “women and children first,” Sex and Age seem like good features to predict survival. Let’s map the text values in the Sex column to a numerical value. Update Sex such that all values female are replaced with 1 and all values male are replaced with 0.

In [3]:
# Using a lambda fuction to map the nmerical values to the 'Sex' column. 
# Although this may be more useful to create a new column.
df['Sex'] = df['Sex'].map(lambda x: 1 if x == 'female' else 0)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

## 3
Let’s take a look at Age. Print passengers['Age'].values. You can see we have multiple missing values, or nans. Fill all the empty Age values in passengers with the mean age.

In [4]:
# we need to look and see how many NaNs there are
df['Age'].isna().sum()

177

In [5]:
# Not I need to covert the NaN to the mean using NumPy
df['Age'].fillna(np.mean(df['Age']), inplace = True)

In [6]:
# Now recheck the NaNs
df['Age'].isna().sum()
# Sorted

0

## 4
Given the strict class system onboard the Titanic, let’s utilize the Pclass column, or the passenger class, as another feature. Create a new column named FirstClass that stores 1 for all passengers in first class and 0 for all other passengers.

In [7]:
# using lambda again to set all first class to 1. Here we use apply vs Map
df['FirstClass'] = df['Pclass'].apply(lambda x: 1 if x ==1 else 0)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  FirstClass  
0         A/5 21171   7.2500   NaN        S           0  
1          PC 17599  71.2833   C85        C           1  
2  STON/O2. 3101282   7.9250   NaN        S           0  
3            113803  53.1000  C123        S           1  
4            373450   8.0500   NaN        S           0

## 5
Create a new column named SecondClass that stores 1 for all passengers in second class and 0 for all other passengers.

Print passengers and inspect the DataFrame to ensure all the updates have been made.

**Mike: ** this just seems like manual one-hot encoding.

In [8]:
# using lambda again to set all second class to 1. Here we use apply vs Map
df['SecondClass'] = df['Pclass'].apply(lambda x: 1 if x ==2 else 0)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  FirstClass  SecondClass  
0         A/5 21171   7.2500   NaN        S           0            0  
1          PC 17599  71.2833   C85        C           1            0  
2  STON/O2. 3101282   7.9250   NaN        S           0            0  
3            113803  53.1000  C123        S           1            0  
4            373450   8.0500   NaN        S           0            0

## 6
Now that we have cleaned our data, let’s select the columns we want to build our model on. Select columns Sex, Age, FirstClass, and SecondClass and store them in a variable named features. Select column Survived and store it a variable named survival.

In [9]:
# Selecting column variables to allow us to generate an X and y set
features_cols = ['Sex', 'Age', 'FirstClass', 'SecondClass']
features = df[features_cols]
survival = df['Survived']
print(features.head())
print(survival.head())

   Sex   Age  FirstClass  SecondClass
0    0  22.0           0            0
1    1  38.0           1            0
2    1  26.0           0            0
3    1  35.0           1            0
4    0  35.0           0            0
0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64


## 7
Split the data into training and test sets using sklearn‘s train_test_split() method. We’ll use the training set to train the model and the test set to evaluate the model.

In [10]:
X_train, X_test, y_train, y_test = train_test_split(features,survival)

## 8
Since sklearn‘s Logistic Regression implementation uses Regularization, we need to scale our feature data. Create a StandardScaler object, .fit_transform() it on the training features, and .transform() the test features.

In [11]:
# normalise the feature data
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

## 9 
Create a LogisticRegression model with sklearn and .fit() it on the training data.

Fitting the model will perform gradient descent to find the feature coefficients that minimize the log-loss for the training data.

In [12]:
# Making a model and training it
cc_lr = LogisticRegression()
cc_lr.fit(X_train, y_train)
y_predict = cc_lr.predict(X_test)


## 10
.score() the model on the training data and print the training score.

Scoring the model on the training data will run the data through the model and make final classifications on survival for each passenger in the training set. The score returned is the percentage of correct classifications, or the accuracy.

In [13]:
# Score the model against the real data
train_score = cc_lr.score(X_train, y_train)
print(f'Training score is {train_score}')
# This is a reasonable score

Training score is 0.7949101796407185


## 11
.score() the model on the test data and print the test score.

Similarly, scoring the model on the testing data will run the data through the model and make final classifications on survival for each passenger in the test set.

How well did your model perform?

In [14]:
# Score the model on the testing data
train_score = cc_lr.score(X_test, y_test)
print(f'Testing score is {train_score}')

Testing score is 0.7802690582959642


## 12
Print the feature coefficients determined by the model. Which feature is most important in predicting survival on the sinking of the Titanic?

In [15]:
print(features.columns)
print(f'Coefficient: {cc_lr.coef_}')
print(f'Intercept: {cc_lr.intercept_}')
#From this model it looks as though the most important feature is the sex, followed by the cabin class.

Index(['Sex', 'Age', 'FirstClass', 'SecondClass'], dtype='object')
Coefficient: [[ 1.29230713 -0.32007898  0.9631492   0.43002572]]
Intercept: [-0.58343744]


## 13
Let’s use our model to make predictions on the survival of a few fateful passengers. Provided in the code editor is information for 3rd class passenger Jack and 1st class passenger Rose, stored in NumPy arrays. The arrays store 4 feature values, in the following order:

- Sex, represented by a 0 for male and 1 for female
- Age, represented as an integer in years
- FirstClass, with a 1 indicating the passenger is in first class
- SecondClass, with a 1 indicating the passenger is in second class

A third array, You, is also provided in the code editor with empty feature values. Uncomment the line containing You and update the array with your information, or the information for some fictitious passenger. Make sure to enter all values as floats with a .!

In [23]:
jack = np.array([0., 20., 0., 0.])
rose = np.array([1., 17., 1., 0.])
mike = np.array([0., 32., 1., 0.])
ali = np.array([1., 30., 0., 1.])
pat = np.array([0., 31., 0., 1.])

name_list = ['Jack', 'Rose', 'Mike', 'Ali', 'Pat']

## 14
Combine Jack, Rose, and You into a single NumPy array named sample_passengers.

In [24]:
sample_passengers = np.array([jack, rose, mike, ali, pat])

## 15
Since our Logistic Regression model was trained on scaled feature data, we must also scale the feature data we are making predictions on. Using the StandardScaler object created earlier, apply its .transform() method to sample_passengers and save the result to sample_passengers.

Print sample_passengers to view the scaled features.

In [25]:
sample_passengers = scalar.transform(sample_passengers)
print(sample_passengers)

[[-0.75126747 -0.75408534 -0.57274061 -0.51492865]
 [ 1.33108386 -0.98621629  1.74599108 -0.51492865]
 [-0.75126747  0.17443846  1.74599108 -0.51492865]
 [ 1.33108386  0.01968449 -0.57274061  1.94201662]
 [-0.75126747  0.09706147 -0.57274061  1.94201662]]


## 16 
Who will survive, and who will sink? Use your model’s .predict() method on sample_passengers and print the result to find out.

Want to see the probabilities that led to these predictions? Call your model’s .predict_proba() method on sample_passengers and print the result. 
- The 1st column is the probability of a passenger perishing on the Titanic, 
- and the 2nd column is the probability of a passenger surviving the sinking (which was calculated by our model to make the final classification decision).

In [26]:
sample_predict = cc_lr.predict(sample_passengers)
sample_proba = cc_lr.predict_proba(sample_passengers)
for index in range(len(name_list)):
    print(f'Survival for {name_list[index]} is {str(sample_predict[index])} with a probability of {str(sample_proba[index])}.')

Survival for Jack is 0 with a probability of [0.88953559 0.11046441].
Survival for Rose is 1 with a probability of [0.05153341 0.94846659].
Survival for Mike is 0 with a probability of [0.53741057 0.46258943].
Survival for Ali is 1 with a probability of [0.19561752 0.80438248].
Survival for Pat is 0 with a probability of [0.786153 0.213847].


In [27]:
sample_proba

array([[0.88953559, 0.11046441],
       [0.05153341, 0.94846659],
       [0.53741057, 0.46258943],
       [0.19561752, 0.80438248],
       [0.786153  , 0.213847  ]])